### PR TITLE
Add messeages components

### PR DESCRIPTION
**Pull request by GUCCSEN1073**
this is intended to fulfil having the messaging part functional . However, I  did  account only for the happy path and no handling for edge cases but I believe that it could be good enough to submit.  

to test it you'll have to run the server + messages service, you'll also need to mock the current user and the visited user objects since it's not handled anywhere. 

screen shot 2018-04-07 at 05 26 06

I also left the component call in the index page. Feel free to fix the conflict since you may be aware more of your last changes. 

Thanks :)

### CODE REVIEW

**Comment by aaeabdo** [comment]
you shall use the latest master of the messages service https://github.com/GUCCSEN1073/YoutubeBananaMessages

**Comment by GUCCSEN1073** [comment]
you shall use the latest master of the messages service https://github.com/GUCCSEN1073/YoutubeBananaMessages

**Comment by ninesalt** [comment]
I see you included jquery just to use `forEach`. If you don't think we're going to need jquery in the future then please just use a regular `forEach` to make the bundle size smaller.

**Comment by GUCCSEN1073** [comment]
@ninesalt good point, been long time since I touched frontend stuff, I'll remove the dependency and fix the conflicts.

**Comment by GUCCSEN1073** [comment]
all is good now, @ninesalt you can merge it!

**Pull request merged**
